### ISSUE TITLE
full example installer binary would be useful

### ISSUE THREAD

**Issue by goofyseeker311** [sockitfpga/MiSTer_SoCkit#1]
similar to the main mister github repository, there should be an installable package that can be installed directly to arrow sockit without any compiling tasks. reasons: ux friendliness and testing.

**Comment by somhi** [comment]
Hi!  Are you asking for an updateall script akin to MiSTer to update all cores from sdcard ?
I'm afraid that is not planned but you or anyone are welcome to contribute.

**Comment by goofyseeker311** [comment]
well I happened to already do like the instructions said, but if the install package that has all what the instructions said by automation would be nice. it would be very much simpler for the user if the install package was all that is needed, no manual editing anything.

anyways, the sockit mister does not like at least 4 config parameters of the newest mister devel.

**Comment by goofyseeker311** [comment]
also if you want to make things easy, automatic porting of the current cores, even with the litex fpga adapter, or just automated per core porting, would not task you in any extra work. automation is the king.

**Comment by somhi** [comment]
You are very wellcome to contribute in this project.

**Comment by goofyseeker311** [comment]
ok, lets see what should be done and how, if at all, a bit later.

one relatively simple option would be to make an iso/dd of a snapshot of an sd card, then any linux/rufus/disk tool could be used to flash the sd card or an usb stick.

another option is to take the newest mister sd card installer, and replace the files on it, directly, then re-package.

**Comment by goofyseeker311** [comment]
oh really github, normal user gets max 25mb files? this one is 122mb.

**Comment by goofyseeker311** [comment]
ever tried to port the new n64 (mister64) core to mister sockit?

also the link to noemi's github does not work, deleted github account?

**Comment by somhi** [comment]
not me, but Noemí did I think. I told Noemí to check this link

**Comment by goofyseeker311** [comment]
omg the 128mb stick from the ultimate mister does not fit directly to the p0033 gpio socket

**Comment by somhi** [comment]
There is a telegram discussion group  https://t.me/Sockit_FPGA   if you want to join also

**Comment by goofyseeker311** [comment]
sure, and I just broke off the p0033 gpio socket side walls, now the 128mb v3 sdram system works, nes works, memtest/sdram tests all work. I'll try other cores, like snes, and see if they all work properly, with some roms.

edit: snes, gameboy works.

I also made some updates on my fork, like adding images, links etc. also with that windows installer .rar package.

**Comment by goofyseeker311** [comment]
any problems loading psx cue/bin in zip files?

**Comment by somhi** [comment]
I'm not really a tester guy. Better ask in telegram, although it's not much active, there are few users there who might know

**Comment by goofyseeker311** [comment]
just playing, and I got the psx roms working. mostly. the ecm.

**Comment by somhi** [comment]
Great!   you can freely speak in English there. I'm sure they'll like to know your findings.

**Comment by goofyseeker311** [comment]
dont mind me, I also just like to leave findings and comments even if none responds to them :)
